// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolPrimaProject.Model;

#nullable disable

namespace SchoolPrimaProject.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20221010092526_sample")]
    partial class sample
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolPrimaProject.Model.Marks", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("Marks_Value")
                        .HasColumnType("float");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("Subject_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("SchoolPrimaProject.Model.School", b =>
                {
                    b.Property<int>("School_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("School_Id"));

                    b.Property<string>("School_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("School_Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            SchoolId = 1,
                            SchoolAddress = "Kurunegala",
                            SchoolName = "Maliyadeva  College"
                        },
                        new
                        {
                            SchoolId = 2,
                            SchoolAddress = "Panadura",
                            SchoolName = "President s College"
                        });
                });

            modelBuilder.Entity("SchoolPrimaProject.Model.Studen", b =>
                {
                    b.Property<int>("Student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_id"));

                    b.Property<int>("School_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Student_Dob")
                        .HasColumnType("datetime2");

                    b.Property<int>("Student_Grade")
                        .HasColumnType("int");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_id");

                    b.ToTable("Studens");
                });

            modelBuilder.Entity("SchoolPrimaProject.Model.Subject", b =>
                {
                    b.Property<int>("Subject_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Subject_id"));

                    b.Property<string>("Subject_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Subject_id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolPrimaProject.Model.Teacher", b =>
                {
                    b.Property<int>("Teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Teacher_id"));

                    b.Property<int>("School_Id")
                        .HasColumnType("int");

                    b.Property<int>("Subject_id")
                        .HasColumnType("int");

                    b.Property<string>("Teacher_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Teacher_id");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
